### ISSUE TITLE
how can chef-brigade help?

### ISSUE THREAD

**Issue by josephholsten** [chef-brigade/dhcp-cookbook#50]
We're working on a number of ways to help cookbooks, and the existing stuff is in https://github.com/chef-brigade/meta

But is there anything in particular `dhcp` needs help with? Common things:
- testing
- release process
- handling open PRs
- usage doc
- contributing doc

**Comment by acranox** [comment]
IMHO, this cookbook could benefit from some basic housekeeping.  The dynamic DNS library is incomplete, and won't actually read in the keys from attributes, because of a conditional that can never be matched.  I fell down this rabbit hole once.

The failover logic is also a mess.  It stores the masters in an array of hashes, but will only pull the first one from the array, and then keys off the field 'ipaddress' which is the only field used (so why not just use a simple array?) and dhcpd allows setting the peer to a hostname, so why is this field even called ipaddress?  And if it's determined that the host is neither a master or a slave, but failover is enabled, the subnets have the peer line added, but it doesn't get put into the dhcpd.conf, which results in a scenario where dhcpd won't start.

**Comment by jmccann** [comment]
Thanks @acranox for the comments.  We would totally love to review a PR(s) to address those issues.  As for me, I don't use those features currently myself so don't see myself putting any time into it ... unless in the form of reviewing something submitted to me.  :wink:
